<?php
/**
 * AccountAnalyticsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Talon.One API
 *
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TalonOne\Client;

use PHPUnit\Framework\TestCase;

/**
 * AccountAnalyticsTest Class Doc Comment
 *
 * @category    Class
 * @description AccountAnalytics
 * @package     TalonOne\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AccountAnalyticsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AccountAnalytics"
     */
    public function testAccountAnalytics()
    {
    }

    /**
     * Test attribute "applications"
     */
    public function testPropertyApplications()
    {
    }

    /**
     * Test attribute "active_campaigns"
     */
    public function testPropertyActiveCampaigns()
    {
    }

    /**
     * Test attribute "campaigns"
     */
    public function testPropertyCampaigns()
    {
    }

    /**
     * Test attribute "coupons"
     */
    public function testPropertyCoupons()
    {
    }

    /**
     * Test attribute "active_coupons"
     */
    public function testPropertyActiveCoupons()
    {
    }

    /**
     * Test attribute "expired_coupons"
     */
    public function testPropertyExpiredCoupons()
    {
    }

    /**
     * Test attribute "custom_attributes"
     */
    public function testPropertyCustomAttributes()
    {
    }

    /**
     * Test attribute "referral_codes"
     */
    public function testPropertyReferralCodes()
    {
    }

    /**
     * Test attribute "active_referral_codes"
     */
    public function testPropertyActiveReferralCodes()
    {
    }

    /**
     * Test attribute "expired_referral_codes"
     */
    public function testPropertyExpiredReferralCodes()
    {
    }

    /**
     * Test attribute "users"
     */
    public function testPropertyUsers()
    {
    }

    /**
     * Test attribute "roles"
     */
    public function testPropertyRoles()
    {
    }

    /**
     * Test attribute "webhooks"
     */
    public function testPropertyWebhooks()
    {
    }

    /**
     * Test attribute "loyalty_programs"
     */
    public function testPropertyLoyaltyPrograms()
    {
    }

    /**
     * Test attribute "active_rules"
     */
    public function testPropertyActiveRules()
    {
    }
}
