<?php
/**
 * CampaignAnalyticsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerSession](https://docs.talon.one/integration-api/#operation/updateCustomerSessionV2) endpoint is `https://mycompany.talon.one/v2/customer_sessions/{Id}`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TalonOne\Client;

use PHPUnit\Framework\TestCase;

/**
 * CampaignAnalyticsTest Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     TalonOne\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CampaignAnalyticsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CampaignAnalytics"
     */
    public function testCampaignAnalytics()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "campaignRevenue"
     */
    public function testPropertyCampaignRevenue()
    {
    }

    /**
     * Test attribute "totalCampaignRevenue"
     */
    public function testPropertyTotalCampaignRevenue()
    {
    }

    /**
     * Test attribute "campaignRefund"
     */
    public function testPropertyCampaignRefund()
    {
    }

    /**
     * Test attribute "totalCampaignRefund"
     */
    public function testPropertyTotalCampaignRefund()
    {
    }

    /**
     * Test attribute "campaignDiscountCosts"
     */
    public function testPropertyCampaignDiscountCosts()
    {
    }

    /**
     * Test attribute "totalCampaignDiscountCosts"
     */
    public function testPropertyTotalCampaignDiscountCosts()
    {
    }

    /**
     * Test attribute "campaignRefundedDiscounts"
     */
    public function testPropertyCampaignRefundedDiscounts()
    {
    }

    /**
     * Test attribute "totalCampaignRefundedDiscounts"
     */
    public function testPropertyTotalCampaignRefundedDiscounts()
    {
    }

    /**
     * Test attribute "campaignFreeItems"
     */
    public function testPropertyCampaignFreeItems()
    {
    }

    /**
     * Test attribute "totalCampaignFreeItems"
     */
    public function testPropertyTotalCampaignFreeItems()
    {
    }

    /**
     * Test attribute "couponRedemptions"
     */
    public function testPropertyCouponRedemptions()
    {
    }

    /**
     * Test attribute "totalCouponRedemptions"
     */
    public function testPropertyTotalCouponRedemptions()
    {
    }

    /**
     * Test attribute "couponRolledbackRedemptions"
     */
    public function testPropertyCouponRolledbackRedemptions()
    {
    }

    /**
     * Test attribute "totalCouponRolledbackRedemptions"
     */
    public function testPropertyTotalCouponRolledbackRedemptions()
    {
    }

    /**
     * Test attribute "referralRedemptions"
     */
    public function testPropertyReferralRedemptions()
    {
    }

    /**
     * Test attribute "totalReferralRedemptions"
     */
    public function testPropertyTotalReferralRedemptions()
    {
    }

    /**
     * Test attribute "couponsCreated"
     */
    public function testPropertyCouponsCreated()
    {
    }

    /**
     * Test attribute "totalCouponsCreated"
     */
    public function testPropertyTotalCouponsCreated()
    {
    }

    /**
     * Test attribute "referralsCreated"
     */
    public function testPropertyReferralsCreated()
    {
    }

    /**
     * Test attribute "totalReferralsCreated"
     */
    public function testPropertyTotalReferralsCreated()
    {
    }

    /**
     * Test attribute "addedLoyaltyPoints"
     */
    public function testPropertyAddedLoyaltyPoints()
    {
    }

    /**
     * Test attribute "totalAddedLoyaltyPoints"
     */
    public function testPropertyTotalAddedLoyaltyPoints()
    {
    }

    /**
     * Test attribute "deductedLoyaltyPoints"
     */
    public function testPropertyDeductedLoyaltyPoints()
    {
    }

    /**
     * Test attribute "totalDeductedLoyaltyPoints"
     */
    public function testPropertyTotalDeductedLoyaltyPoints()
    {
    }
}
