<?php
/**
 * IntegrationStateV2Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Talon.One API
 *
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * IntegrationStateV2Test Class Doc Comment
 *
 * @category    Class
 * @description Contains all entities that might interest Talon.One integrations. This is the response type returned by the V2 PUT customer_session endpoint
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class IntegrationStateV2Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IntegrationStateV2"
     */
    public function testIntegrationStateV2()
    {
    }

    /**
     * Test attribute "customer_session"
     */
    public function testPropertyCustomerSession()
    {
    }

    /**
     * Test attribute "customer_profile"
     */
    public function testPropertyCustomerProfile()
    {
    }

    /**
     * Test attribute "event"
     */
    public function testPropertyEvent()
    {
    }

    /**
     * Test attribute "loyalty"
     */
    public function testPropertyLoyalty()
    {
    }

    /**
     * Test attribute "referral"
     */
    public function testPropertyReferral()
    {
    }

    /**
     * Test attribute "coupons"
     */
    public function testPropertyCoupons()
    {
    }

    /**
     * Test attribute "triggered_campaigns"
     */
    public function testPropertyTriggeredCampaigns()
    {
    }

    /**
     * Test attribute "effects"
     */
    public function testPropertyEffects()
    {
    }

    /**
     * Test attribute "created_coupons"
     */
    public function testPropertyCreatedCoupons()
    {
    }

    /**
     * Test attribute "created_referrals"
     */
    public function testPropertyCreatedReferrals()
    {
    }
}
