<?php
/**
 * NewManagementKeyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TalonOne\Client;

use PHPUnit\Framework\TestCase;

/**
 * NewManagementKeyTest Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     TalonOne\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class NewManagementKeyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NewManagementKey"
     */
    public function testNewManagementKey()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "expiryDate"
     */
    public function testPropertyExpiryDate()
    {
    }

    /**
     * Test attribute "endpoints"
     */
    public function testPropertyEndpoints()
    {
    }

    /**
     * Test attribute "allowedApplicationIds"
     */
    public function testPropertyAllowedApplicationIds()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "createdBy"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "accountID"
     */
    public function testPropertyAccountID()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {
    }
}
