<?php
/**
 * SupportRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TalonOne\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TalonOne\Client;

use PHPUnit\Framework\TestCase;

/**
 * SupportRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Summary of a support request created by a customer support agent.
 * @package     TalonOne\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SupportRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SupportRequest"
     */
    public function testSupportRequest()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "applicationId"
     */
    public function testPropertyApplicationId()
    {
    }

    /**
     * Test attribute "campaignId"
     */
    public function testPropertyCampaignId()
    {
    }

    /**
     * Test attribute "loyaltyProgramId"
     */
    public function testPropertyLoyaltyProgramId()
    {
    }

    /**
     * Test attribute "subledgerId"
     */
    public function testPropertySubledgerId()
    {
    }

    /**
     * Test attribute "createdByUser"
     */
    public function testPropertyCreatedByUser()
    {
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "customerProfileId"
     */
    public function testPropertyCustomerProfileId()
    {
    }

    /**
     * Test attribute "requestType"
     */
    public function testPropertyRequestType()
    {
    }

    /**
     * Test attribute "requestValue"
     */
    public function testPropertyRequestValue()
    {
    }

    /**
     * Test attribute "requestNote"
     */
    public function testPropertyRequestNote()
    {
    }

    /**
     * Test attribute "requestStatus"
     */
    public function testPropertyRequestStatus()
    {
    }

    /**
     * Test attribute "processedAt"
     */
    public function testPropertyProcessedAt()
    {
    }

    /**
     * Test attribute "processingNote"
     */
    public function testPropertyProcessingNote()
    {
    }

    /**
     * Test attribute "processedByUser"
     */
    public function testPropertyProcessedByUser()
    {
    }

    /**
     * Test attribute "couponCode"
     */
    public function testPropertyCouponCode()
    {
    }
}
