<?php
/**
 * StorageApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Talon.One API
 *
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * StorageApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StorageApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createStorage
     *
     * Create an application storage.
     *
     */
    public function testCreateStorage()
    {
    }

    /**
     * Test case for createStorageData
     *
     * Create application storage data.
     *
     */
    public function testCreateStorageData()
    {
    }

    /**
     * Test case for deleteStorageValue
     *
     * Delete one application storage value.
     *
     */
    public function testDeleteStorageValue()
    {
    }

    /**
     * Test case for getStorage
     *
     * Get an application storage.
     *
     */
    public function testGetStorage()
    {
    }

    /**
     * Test case for getStorageData
     *
     * Get application storage data.
     *
     */
    public function testGetStorageData()
    {
    }

    /**
     * Test case for getStorageValue
     *
     * Get application storage value.
     *
     */
    public function testGetStorageValue()
    {
    }

    /**
     * Test case for getStorages
     *
     * List application storages.
     *
     */
    public function testGetStorages()
    {
    }

    /**
     * Test case for updateStorage
     *
     * Update an application storage.
     *
     */
    public function testUpdateStorage()
    {
    }

    /**
     * Test case for updateStorageValue
     *
     * Update one application storage value.
     *
     */
    public function testUpdateStorageValue()
    {
    }
}
